BEGIN;

DROP TABLE IF EXISTS  "users", "events", "sports", "users_join_events", "users_like_sports";

CREATE TABLE "users" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "email" VARCHAR (127) NOT NULL,
    "is_admin" BOOLEAN NOT NULL DEFAULT FALSE,
    "user_name" VARCHAR (32) NOT NULL,
    "password" VARCHAR (128) NOT NULL,
    "last_name" VARCHAR (64) NOT NULL,
    "first_name" VARCHAR (64) NOT NULL,
    "region" VARCHAR (64) NOT NULL,
    "zip_code" INTEGER NOT NULL,
    "city" VARCHAR (64) NOT NULL,
    "street" VARCHAR (255),
    "description" VARCHAR (255),
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    "updated_at" TIMESTAMPTZ 
); 

CREATE TABLE "sports" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" VARCHAR (32) NOT NULL
);

CREATE TABLE "events" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "creator_id" INTEGER REFERENCES "users"("id") ON DELETE SET NULL,
    "sport_id" INTEGER REFERENCES "sports"("id") ON DELETE SET NULL,
    "title" VARCHAR (64) NOT NULL,
    "region" VARCHAR (64) NOT NULL,
    "zip_code" INTEGER NOT NULL,
    "city" VARCHAR (64) NOT NULL,
    "street" VARCHAR (255) NOT NULL,
    "description" VARCHAR (500),
    "starting_time" TIMESTAMPTZ NOT NULL,
    "ending_time" TIMESTAMPTZ NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    "updated_at" TIMESTAMPTZ
);

CREATE TABLE "users_join_events" (
    "event_id"  INTEGER NOT NULL REFERENCES "events"("id") ON DELETE CASCADE,
    "user_id"  INTEGER NOT NULL REFERENCES "users"("id") ON DELETE CASCADE
);

CREATE TABLE "users_like_sports" (
    "user_id"  INTEGER NOT NULL REFERENCES "users"("id") ON DELETE CASCADE,
    "sport_id"  INTEGER NOT NULL REFERENCES "sports"("id") ON DELETE CASCADE
);

COMMIT;
